Repository RoBorregos/roborregos-web, pull requests merged in 2020-09, with the labels that each got.

#2 Eliminated ex-members of the project.
  README.md
Labels: good first issue

#3 Make README.md more beginner friendly.
  README.md
Labels: documentation

#25 Feature/development tools jest
  .eslintrc.json
  README.md
  fileTransformer.js
  flow-typed/npm/jest_v26.x.x.js
  jest.config.js
  package.json
  src/App.test.js
  src/components/About/About.js
  src/components/About/AboutHeader/AboutHeader.js
  src/components/About/AboutTimeline/AboutSingleTimelineEvent/AboutSingleTimelineEvent.js
  src/components/Candidates/Candidates.js
  src/components/Candidates/CandidatesCarousel/CandidatesCarousel.js
  src/components/Contact/Contact.js
  src/components/Contact/ContactCompetitions/ContactCompetitions.js
  src/components/Contact/ContactSponsorUs/ContactSponsorPackages/ContactSponsorPackages.js
  src/components/Footer/Footer.js
  src/components/Home/Home.js
  src/components/Home/HomeHeader/HomeHeader.js
  src/components/Home/HomeSponsors/HomeSingleSponsor/HomeSingleSponsor.js
  src/components/Members/Members.js
  src/components/Members/MembersGrid/MemberModal/MemberModal.js
  src/components/Members/MembersGrid/MembersGrid.js
  src/components/NavBar/NavBar.js
  yarn.lock
Labels: enhancement
